name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-bookmaker-api:
    name: Build bookmaker-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmaker-api

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn verify

      - if: ${{ github.ref == 'refs/heads/main }}
        name: Build and publish Docker Image
        run:
          mvn clean package jib:dockerBuild -DskipTests
          docker login -u ${{secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmaker-api